### ISSUE TITLE
How to install different variants

### ISSUE THREAD

**Issue by vikky49** [rojiani/Ligaturizer#1]
Hi 
This is a great utility and really loved it ? But while creating the bold and italic fonts they are being created as totally different fonts . Hence the IDE's wont detect them as a single font. But when i tried installing SFMono and SFMono semi bold in the out put fonts that u have , they seem to be installing as a same font. 

Is there any trick that i have to do to generate all the different variants on the font into same font

**Comment by rojiani** [comment]
I'm not sure if Italics could be supported at this time since FiraCode doesn't have an Italic variant. It does provide Medium and Bold variants, so generating the proper variant based on the input font is something I'll add very soon.

**Comment by ToxicFrog** [comment]
I think I'm hitting the same issue -- I run it using `Cousine-{Regular,Bold,Italic,BoldItalic}.ttf` as inputs, and it generates `Couslig.ttf` and `Couslig-{Bold,Italic,BoldItalic}.ttf`, which are then seen by fontconfig as being four distinct fonts, rather than reglar, bold, italic, and bold+italic variants of the same font.

I'd be ok with just using the Regular ligatures in the Italic font, and Bold in BoldItalic, as a stopgap; it's better than not having any bold or italic support at all.

**Comment by rojiani** [comment]
[Fixed](https://github.com/rojiani/Ligaturizer/pull/11)
