### ISSUE TITLE
====

### ISSUE THREAD

**Issue by duncanwerner** [rojiani/Ligaturizer#2]
I have some block comments (this is R) that look like 

```
#=================================
#
#=================================
```
and so on.  Fira Code renders these as above.  When I try your fonts, they transform these into a set of `===` ligatures.  Not the end of the world, but I would prefer they did not do that.

**Comment by ToxicFrog** [comment]
More generally, Fira Code does something to prevent long runs of identical characters from ligaturizing; it applies not just to `=` but also to `#`, `||`, `-`, and so forth.

I *think* this is implemented with the `ignore sub` rules in the Fira Code CALT table: https://github.com/tonsky/FiraCode/blob/master/gen_calt.clj#L65

I don't know how to copy that over to the ligaturized fonts, though.

**Comment by ToxicFrog** [comment]
Solved it! It results in a lot of worried log spam by fontforge (because it involves creating substitution rules that don't actually substitute anything), but it appears to work, and (apart from using `glyph` instead of `coverage`, which doesn't seem to break anything), the generated ATTs match the ones in the Fira Code OTFs.

I have a patch for this ready to go once #9 is fixed.

**Comment by ToxicFrog** [comment]
If you want to have a go at it yourself, the trick is, after adding all the normal contextual subtables for a ligature (with, say, characters `A B C D`), add two more with no `@<lookup>` clause; one matching `A | A | B C D` and the other matching `| A | B C D D`.

**Comment by rojiani** [comment]
[Fixed](https://github.com/rojiani/Ligaturizer/pull/11). Thanks @ToxicFrog
