### ISSUE TITLE
Out put Font Type Differs from Input Font Type

### ISSUE THREAD

**Issue by vikky49** [rojiani/Ligaturizer#3]
For example lets take Source Code pro font when trying to path the ligatures if the input type is 
Source Code Pro- Regular.otf or ttf and after running the script the output ends up being type 
"Book" ..I am not sure if its intended or a bug , but because of that some IDE's like Intelli J has issues picking up that font (especially Source Code pro)

**Comment by rojiani** [comment]
That is a bug - one i have not seen (I mostly use SF Mono & IBM Plex Mono, which are being picked up by IntelliJ). The script needs some work and I intend to write some unit tests and clean it up when I get the chance. Currently I'm very busy studying for interviews.

For Source Code Pro, though, you are in luck, since there is a ligaturized version of it: check out [Hasklig](https://github.com/i-tu/Hasklig).

**Comment by rojiani** [comment]
Should be [fixed](https://github.com/rojiani/Ligaturizer/pull/11) now. Will close after confirming

**Comment by vikky49** [comment]
@rojiani It looks fixed now .just tested with the problematic fontss
